config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  enum status: {handled: 0, not_handle: 1}
  validates :phone, presence: true, numericality: true
  validates :address, presence: true
  scope :sort_by_id, ->{order :id}
  scope :count_date, ->{order("DATE(created_at)").group("DATE(created_at)")}
  scope :count_month, ->{order("MONTH(created_at)").group("MONTH(created_at)")}
  scope :count_year, ->{order("YEAR(created_at)").group("YEAR(created_at)")}
  scope :find_order, ->(id){where user_id: id}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :load_order, only: %i(edit destroy update show)

  def index
    @orders = Order.sort_by_id
  end

  def show; end

  def destroy
    if @order.destroy
      flash[:success] = t "admin.deleted"
    else
      flash[:warning] = t "admin.notdelete"
    end
    redirect_to admin_orders_path
  end

  def edit; end

  def update
    if @order.update_attributes order_params
      flash[:success] = t "admin.updatesuc"
    else
      flash[:warning] = t "admin.updatefail"
    end
    redirect_to admin_orders_path
  end

  private

  def order_params
    params.require(:order).permit(:status, :phone, :address)
  end

  def load_order
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:warning] = t "users_controller.errorss"
    redirect_to admin_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user, only: :new

  def new
    @oder = Order.new
    @cart = current_cart
    @total = @cart.total_price
    @user = session[:user_id]
  end

  def create
    @oder = Order.new order_params
    if @oder.save
      UserMailer.mailer_order(@oder).deliver_now
      create_order
      destroy_session session[:cart_id]
      session[:cart_id] = nil
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @order = Order.find_order session[:user_id]
  end

  def order_params
    params.require(:order).permit(:total_amount, :user_id, :phone, :address)
  end

  private

  def create_order
    @item = current_cart.line_items
    ActiveRecord::Base.transaction do
      @item.each do |cate|
        OrderDetail.create!(order_id: @oder.id, product_id: cate.product_id, quanlity: cate.quantity)
        update_product cate
      end
    end
    flash[:success] = t "orders_controller.create"
  rescue
    flash[:error] = t "orders_controller.errror"
  end

  def update_product cate
    @product = Product.find_by id: cate.product_id
    @product.update_attributes! quanlity: (@product.quanlity - cate.quantity) if @product
  end
end

app/views/admin/orders/_order.html.erb
<tr>
    <td><%= order.user.name %></td>
    <td><%= order.phone %></td>
    <td><%= order.address %></td>
    <td><%= order.total_amount %></td>
    <td>
    <span class="label label-warning">
      <%= order.status %>
    </span>
    </td>
    <td><%= order.created_at.to_date %></td>
    <td><%= order.updated_at.to_date %></td>
    <td>
    <%= link_to "", admin_order_path(order), method: :delete,
      class: "fa fa-trash-o btn btn-danger", data: {confirm: (t "users.index.sure") } %>
    <%= link_to "", admin_orderdetail_path(order), class: "fa fa-info btn btn-danger" %>
    <%= link_to "", edit_admin_order_path(order.id),
      class: "fa fa-pencil-square-o btn btn-danger" %>
    </td>
</tr>

app/views/admin/orders/edit.html.erb
<% provide(:title, (t "admin.order.titleupdate")) %>
<h1><%= t "admin.order.titleupdate" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @order] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :status %>
      <%= f.select :status, Order.statuses.map{|key, value| [t("status_#{key}"), key]},
        {}, {class: "form-control"} %>

      <%= f.label :phone %>
      <%= f.number_field :phone, class: "form-control" %>

      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>

      <%= f.submit (t "admin.order.update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<% provide(:title, t("admin.order.title")) %>
<h1><%= t "admin.order.title" %></h1>
<div class="table-responsive">
  <table class="table">
    <%= link_to (t "admin.statistic.title"), admin_statistics_path, class: "btn btn-primary" %>
    <thead>
      <tr>
        <th><%= t "admin.order.person" %></th>
        <th><%= t "admin.order.phone" %></th>
        <th><%= t "admin.order.address" %></th>
        <th><%= t "admin.order.totala" %></th>
        <th><%= t "admin.order.status" %></th>
        <th><%= t "admin.order.create" %></th>
        <th><%= t "admin.order.update" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "order", collection: @orders %>
    </tbody>
  </table>
</div>