config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product product_id
    current_item = line_items.find_by product_id: product_id
    if current_item.blank?
      current_item = line_items.build product_id: product_id
    elsif current_item.quantity < current_item.product.quanlity
      current_item.quantity += 1
    end
    current_item
  end

  def decrease_product product_id
    current_item = line_items.find_by product_id: product_id
    current_item.quantity -= 1 if current_item.quantity > 1
    current_item
  end

  def total_price
    line_items.sum(&:total_price_product)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :ses_cart, only: %i(show index)

  def index; end

  def show; end

  def create; end

  def destroy
    @cart = current_cart
    if @cart.destroy
      session[:cart_id] = nil
      flash[:warning] = t "static_pages_controller.eror_nilcart"
      redirect_to root_url
    else
      flash[:warning] = t "static_pages_controller.carts"
      redirect_to cartyour_path
    end
  end

  private

  def ses_cart
    @cart = Cart.find_by(id: session[:cart_id])
    return if @cart
    flash[:warning] = t "static_pages_controller.carts"
    redirect_to root_url
  end
end

app/views/carts/_cart.html.erb
 <tr>
  <td class="cart_product">
    <%= image_tag(cart.product.image, size:Settings.size.cart) %>
  </td>
  <td class="cart_description">
    <p><%= cart.product.name %></p>
  </td>
  <td class="cart_quantity">
    <%= link_to t("add"), items_path(product_id: cart.product.id),
    class:"btn btn-success",method: :post ,remote:true %>
    <%= cart.quantity %>
    <%= link_to t("remove"), line_item_path(product_id: cart.product.id),
    class:"btn btn-success", method: :put ,remote:true %>
  </td>
  <td class="cart_total">
    <p class="cart_total_price"><%= cart.product.price %></p>
  </td>
   <td class="cart_total">
    <p class="cart_total_price"><%= cart.quantity * cart.product.price %></p>
  </td>
  <td>
    <%= link_to deleteitem_path(id: cart.id), method: :delete, remote:true, class: "add-to-cart pull-left" do %>
      <i class="fa fa-trash-o" aria-hidden="true" ></i>
    <% end %>
  </td>
</tr>

app/views/carts/show.html.erb
<h2><%= t"carts.show.cart" %></h2>
<div class="row">
  <%= link_to t("carts.show.delete_cart"), @cart, method: :delete,
  data: {confirm: t("carts.show.eror")} , class: "btn btn-info" %>
</div>
<div class="table-responsive cart_info">
  <table class="table table-condensed">
    <thead>
      <tr class="cart_menu">
        <td class="image"><%= t"carts.show.image" %></td>
        <td class="price"><%= t"carts.show.name" %></td>
        <td class="quantity"><%= t"carts.show.quanlity" %></td>
        <td class="total"><%= t"carts.show.price" %></td>
        <td class="total"><%= t"carts.show.sum" %></td>
        <td><%= t"carts.show.action" %></td>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "cart", collection: @cart.line_items %>
    </tbody>
  </table>
</div>
<div class="cart-totals pull-right">
  <div class="cart-totals-row">
    <h5 class="cart-total-title"><%= t"carts.show.cart_total" %>
    </h5>
  </div>
  <div class="cart-totals-row">
    <span>
      <%= t"carts.show.sub_total"%>
    </span>
    <span>
      <%= number_to_currency(@cart.total_price) %>
    </span>
  </div>
  <div class="cart-totals-row">
    <span>
      <%= t"carts.show.ship"%>
    </span>
    <span>
      <%= t"carts.show.free"%>
    </span>
  </div>
</div>
<div class="row">
    <%= link_to root_path, class: "btn btn-warning" do %>
      <%= t "carts.show.continue" %>
      <i class="fa fa-angle-left" aria-hidden="true" ></i>
    <% end %>
    <%= link_to new_order_path, class: "btn btn-warning" do %>
      <%= t "carts.show.order" %>
      <i class="fa fa-angle-left" aria-hidden="true" ></i>
    <% end %>
</div>