config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :line_items, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: Settings.product.price}
  validates :quanlity, presence: true, numericality: {greater_than_or_equal_to: Settings.product.quanlity}
  validates :information, presence: true, length: {maximum: Settings.product.information}
  scope :sort_by_product, ->{order "created_at DESC"}
  scope :sort_by_products, ->{order :name}
  scope :not_original, ->(id){where.not(id: id)}
  scope :find_category, ->(q){where category_id: q if q.present?}
  scope :search_by_name, ->(content){where(" name like ?", "%#{content}%") if content.present?}
  scope :search_price, ->(prices){where(price: prices) if prices.present?}

  scope :product_hot, ->{joins(:order_details)
    .where("MONTH(order_details.created_at) = ?", Date.today.month)
    .group("products.id").order("sum(order_details.quanlity) DESC")   }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :admin_user, only: :destroy
  before_action :load_product, only: %i(destroy edit update)

  def show; end

  def index
    @product = Product.find_category(params[:q])
    @products = Product.sort_by_products
    @categories = Category.sort_by_category
  end

  def new
    @product = Product.new
    @cate = Category.sort_by_category
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "admin.create"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @cate = Category.sort_by_category
  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = t "admin.updatesuc"
    else
      flash[:warning] = t "admin.updatefail"
    end
    redirect_to admin_products_path
  end

  def destroy
    if @product.destroy
      flash[:success] = t "admin.deleted"
    else
      flash[:warning] = t "admin.notdelete"
    end
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :quanlity, :image, :information, :category_id)
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:warning] = t "users_controller.errorss"
    redirect_to admin_products_path
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :load_data, only: :show

  def show
    if @product
      @related_products = Product.not_original(params[:id]).sort_by_product.take(Settings.related_product.config)
      @new_products = Product.sort_by_product.take(Settings.new_product.config)
    else
      flash[:warning] = t "static_pages_controller.errors"
      redirect_to root_url
    end
  end

  private

  def load_data
    @product = Product.find_by id: params[:id]
    @ratings = Rating.show_ratings(params[:id]).order_vote
    @comments = Rating.show_comment(params[:id]).order_created
      .paginate(page: params[:page], per_page: Settings.comment.config)
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td><%= image_tag(product.image, size: Settings.image.admin) %></td>
  <td><%= product.price %></td>
  <td><%= product.category.name %></td>
  <td><%= product.created_at.to_date %></td>
  <td><%= product.updated_at.to_date %></td>
  <td>
  <%= link_to admin_product_path(product), method: :delete,
    class: "fa fa-trash-o btn btn-danger", data: {confirm: (t "users.index.sure") } do %>
  <% end %>
  <%= link_to edit_admin_product_path(product),
    class: "fa fa-pencil-square-o btn btn-danger" do %>
  <% end %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<% provide(:title, (t "admin.product.titleupdate")) %>
<h1><%= t "admin.product.titleupdate" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>

      <%= f.label :quanlity %>
      <%= f.number_field :quanlity, class: "form-control" %>

      <%= f.label :information %>
      <%= f.text_area :information, class: "form-control" %>

      <%= f.label :category %>
      <%= f.collection_select :category_id, @cate, :id, :name, {}, {class: "form-control"} %>

      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>

      <%= f.submit (t "admin.product.update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide(:title, t("admin.product.product")) %>
<h1><%= t "admin.product.product" %></h1>
<div class="form-group">
  <div class = "row">
    <div class = "col-sm-2">
      <%=  form_tag(admin_products_path, method: "get") do %>
        <div class="form-group">
          <%= select_tag :q, options_from_collection_for_select(@categories, :id, :name) ,
            class: "form-control"%>
          <%= submit_tag (t "admin.search"), class: "btn btn-success btn-sm"%>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class = "row">
<div class="table-responsive">
<table class="table">
    <%= link_to "", new_admin_product_path, class: "fa fa-plus fa-1x  btn btn-primary" %>
    <thead>
      <tr>
        <th><%= t "admin.id" %></th>
        <th><%= t "admin.name" %></th>
        <th><%= t "admin.image" %></th>
        <th><%= t "admin.price" %></th>
        <th><%= t "admin.category.category" %></th>
        <th><%= t "admin.createat" %></th>
        <th><%= t "admin.update" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% if @product.present? %>
        <%= render partial: "product", collection: @product %>
      <% else %>
        <%= render partial: "product", collection: @products %>
      <% end %>
    </tbody>
</table>
</div>
</div>

app/views/admin/products/new.html.erb
<% provide(:title, (t "admin.product.title")) %>
<h1><%= t "admin.product.title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>

      <%= f.label :quanlity %>
      <%= f.number_field :quanlity, class: "form-control" %>

      <%= f.label :information %>
      <%= f.text_area :information, class: "form-control" %>

      <%= f.label :category %>
      <%= f.collection_select :category_id, @cate, :id, :name, {}, {class: "form-control"} %>

      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>

      <%= f.submit (t "admin.product.create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>