config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  scope :order_iduser, ->{order :user_id}
end

app/controllers/admin/suggests_controller.rb
class Admin::SuggestsController < ApplicationController
  before_action :load_suggest, only: %i(destroy show)

  def index
    @suggests = Suggest.order_iduser.paginate(page: params[:page],
      per_page: Settings.suggest.per_page)
  end

  def show; end

  def destroy
    if @suggest.destroy
      flash[:success] = t "admin.deleted"
    else
      flash[:warning] = t "admin.notdelete"
    end
    redirect_to admin_suggests_path
  end

  private

  def suggest_params
    params.require(:suggest).permit(:content, :user_id)
  end

  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    return if @suggest
    flash[:warning] = t "users_controller.errorss"
    redirect_to admin_products_path
  end
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  before_action :load_suggest, only: %i(edit destroy show)

  def index; end

  def show; end

  def new
    @suggest = current_user.suggests.build
  end

  def create
    @suggest = current_user.suggests.new suggest_params
    if @suggest.save
      flash[:success] = t "admin.create"
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def suggest_params
    params.require(:suggest).permit(:content)
  end

  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    return if @suggest
    flash[:warning] = t "users_controller.errorss"
    redirect_to admin_products_path
  end
end

app/helpers/admin/suggests_helper.rb
module Admin::SuggestsHelper
end

app/helpers/suggests_helper.rb
module SuggestsHelper
end

app/views/admin/suggests/_suggest.html.erb
<tr>
  <td><%= suggest.user.name %></td>
  <td><%= suggest.user.phone %></td>
  <td><%= suggest.user.address %></td>
  <td><%= suggest.created_at.to_date %></td>
  <td><%= suggest.updated_at.to_date %></td>
  <td>
  <%= link_to "", admin_suggest_path(suggest), method: :delete,
    class: "fa fa-trash-o btn btn-danger", data: {confirm: (t "users.index.sure") } %>
  <%= link_to "", admin_suggest_path(suggest), class: "fa fa-info btn btn-danger" %>
  </td>
</tr>

app/views/admin/suggests/index.html.erb
<% provide(:title, t("admin.suggest.title")) %>
<h1><%= t "admin.suggest.title" %></h1>
<div class="table-responsive">
<table class="table">
    <thead>
      <tr>
        <th><%= t "admin.order.person" %></th>
        <th><%= t "admin.order.phone" %></th>
        <th><%= t "admin.order.address" %></th>
        <th><%= t "admin.order.create" %></th>
        <th><%= t "admin.order.update" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @suggests %>
    </tbody>
    <%= will_paginate @suggests %>
</table>
</div>

app/views/admin/suggests/show.html.erb
<h6><%= t "admin.order.name" %><%= @suggest.user.name %></h6>
<h6><%= t "admin.suggest.content" %></h6>
<%= @suggest.content %>